### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by sqrdcat**
Replace the git.popcorntime.io git repositories with github ones, since the popcorntime git appears to be dead atm

### CODE REVIEW

**Comment by RobinvdGriend** [comment]
Just giving a heads up, when I try to build with your fork I get an error when it tries to reach https://git.popcorntime.io/popcorntime/themes.git/

I'm unfamiliar with this codebase so I don't know where I could find the reference to this resource.

**Comment by xaiki** [comment]
sorry I had to push to clean history, can you refresh this pr ?

**Comment by hadim** [comment]
I included theses changes in my PR (in package.json). So you can close here.

**Comment by xaiki** [comment]
@hadim feel free to close PRs =)

**Pull request closed without merging**
