### PR TITLE
Gruntfile update

### PR DESCRIPTION
**Pull request by MrAdder**
- Grunt start now works for win32 built on win64 #26
- Possible fix for Mac Builds #32 #31 #30

### CODE REVIEW

**Comment by douglascamata** [comment]
@MrAdder will test mac build fix right now.

**Comment by MrAdder** [comment]
replace current gruntfile with this and then do grunt start

**Comment by douglascamata** [comment]
@MrAdder you fix didn't work. I used this, from butterproject/butter#36 and it worked:

```
diff --git a/Gruntfile.js b/Gruntfile.js
index cf9b1e7..0e9315d 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -231,7 +231,7 @@ module.exports = function (grunt) {
                 cmd: '"build/cache/win/<%= nwjs.options.version %>/nw.exe" .'
             },
             mac: {
-                cmd: 'build/cache/mac/<%= nwjs.options.version %>/nwjs.app/Contents/MacOS/nwjs .'
+                cmd: 'cache/<%= nwjs.options.version %>/osx64/nwjs.app/Contents/MacOS/nwjs .'
             },
             linux32: {
                 cmd: '"build/' + projectName + '/linux32/' + projectName + '" .'
```

**Comment by MrAdder** [comment]
Ok will update as We have to "Detect" wich arch your using 32bit/64bit so we are not hardcoding for ALL OSX's

**Comment by douglascamata** [comment]
@MrAdder doesn't need, imho. If you got a Core 2 Duo, or more recent processor, and is running OS X Snow Leopard 10.6, or more recent OS X, you will be running 64 bits. I don't believe people still use OS X Leopard 10.5 :P

**Comment by MrAdder** [comment]
Am going off of the same policy for  Windows 32bit/64bit as the original change was to Hardcode the Path which got denied

**Comment by MrAdder** [comment]
This commit was made possible by the works of @paulhobbel myself and @edospadoni

**Comment by paulhobbel** [comment]
Finally it works ahaha

**Comment by SrPatinhas** [comment]
@MrAdder @paulhobbel can i Merge? :p

**Comment by MrAdder** [comment]
Yes Clear to merge

**Pull request merged**
