### PR TITLE
Don't know why this reverted

### PR DESCRIPTION
**Pull request by paulhobbel**
I don't know what happened but someone reverted changes that were made to this file

### CODE REVIEW

**Comment by paulhobbel** [comment]
Wtf...

**Comment by paulhobbel** [comment]
Well @xaiki guess u have to look into it haha

**Comment by matthewbauer** [comment]
Someone keeps rewriting the history. Please stop with the force updates!

**Comment by matthewbauer** [comment]
Someone keeps rewriting the history. Please stop with the force updates!

**Comment by douglascamata** [comment]
Looks like someone is pushing with __force__ (lol). You should protect the master branch to avoid this.

**Pull request merged**
