### PR TITLE
Fix 'grunt start' error on OSX

### PR DESCRIPTION
**Pull request by szymanskip**
This fix wasn't included in #34

### CODE REVIEW

**Comment by MrAdder** [comment]
Thank you for that am sure @SrPatinhas can merge this must of had an editor glitch on my end

**Comment by paulhobbel** [comment]
Thank you me and @MrAdder didn't notice this

**Comment by MrAdder** [comment]
Had dev enviroment set for different language :) but all is good

**Comment by fijimunkii** [comment]
:+1:

**Pull request merged**
