### PR TITLE
gruntfile start. fixed mac os x el capitan error

### PR DESCRIPTION
**Pull request by edospadoni**
refs:
fix for: https://github.com/butterproject/butter/issues/32
fix for: https://github.com/butterproject/butter/issues/31
fix for: https://github.com/butterproject/butter/issues/30

### CODE REVIEW

**Comment by douglascamata** [comment]
Duplicate of butterproject/butter#34. Can you, please, close to avoid pull requests spam?

**Comment by edospadoni** [comment]
Your commit doesn't fix the Mac OS X problem.

**Comment by douglascamata** [comment]
do you mind closing this and keep following butterproject/butter#34? Your fixes were added there and we are also addressing other problems in the build/packing there.

**Comment by MrAdder** [comment]
Included this fix with other fixes in https://github.com/butterproject/butter/pull/34

**Comment by xaiki** [comment]
fixed in c38db580dc21c8db94370e631c3c10776383309e

**Pull request closed without merging**
